name: Docker Build and Push

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_VPS_SSH_HOST }}
          username: ${{ secrets.DEV_VPS_SSH_USERNAME }}
          key: ${{ secrets.DEV_VPS_SSH_SECRET }}
          port: ${{ secrets.DEV_VPS_SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.DEV_PROJECT_PATH }}
            git fetch
            git checkout develop
            git pull
            docker system prune -af
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker build -t ${{ secrets.DOCKERHUB_REPO }}:develop-youpass .
            docker push ${{ secrets.DOCKERHUB_REPO }}:develop-youpass
            docker system prune -af

      - name: Pull image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_VPS_SSH_HOST }}
          username: ${{ secrets.DEV_VPS_SSH_USERNAME }}
          key: ${{ secrets.DEV_VPS_SSH_SECRET }}
          port: ${{ secrets.DEV_VPS_SSH_PORT }}
          script: |
            cd ${{ secrets.DEV_PROJECT_PATH }}
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker-compose pull
            docker-compose up -d